[[main]]
name = "Yordam olish"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "Hayriya qilish"
weight = 30
identifier = "donate"
url = "/donate/"
[[main]]
name = "Biz haqimizda"
weight = 40
identifier = "about"
url = "/about/"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "Xizmat holati"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Karyera"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
